apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitops-reverse-engineer.fullname" . }}-config
  namespace: {{ include "gitops-reverse-engineer.namespace" . }}
  labels:
    {{- include "gitops-reverse-engineer.labels" . | nindent 4 }}
data:
  config.yaml: |
    watch:
      clusterWideResources: {{ .Values.watch.clusterWideResources }}
      namespaces:
        include: {{ toJson .Values.watch.namespaces.include }}
        exclude: {{ toJson .Values.watch.namespaces.exclude }}
        includePattern: {{ toJson .Values.watch.namespaces.includePattern }}
        excludePattern: {{ toJson .Values.watch.namespaces.excludePattern }}
        labelSelector: {{ toJson .Values.watch.namespaces.labelSelector }}
      resources:
        include: {{ toJson .Values.watch.resources.include }}
        exclude: {{ toJson .Values.watch.resources.exclude }}
      excludeUsers: {{ toJson .Values.watch.excludeUsers }}
    metrics:
      enabled: {{ .Values.metrics.enabled }}
      port: {{ .Values.metrics.port }}
      path: "{{ .Values.metrics.path }}"
