apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "gitops-reverse-engineer.namespace" . }}
  labels:
    {{- include "gitops-reverse-engineer.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
