{{- if not .Values.git.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitops-reverse-engineer.gitSecretName" . }}
  namespace: {{ include "gitops-reverse-engineer.namespace" . }}
  labels:
    {{- include "gitops-reverse-engineer.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.git.token | b64enc | quote }}
{{- end }}
---
{{- if not .Values.tls.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitops-reverse-engineer.tlsSecretName" . }}
  namespace: {{ include "gitops-reverse-engineer.namespace" . }}
  labels:
    {{- include "gitops-reverse-engineer.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
{{- end }}
