#!/bin/bash

set -e

# Helm-integrated certificate generation script
# This script generates certificates and creates a values override file

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_DIR=$( cd -- "$SCRIPT_DIR/.." && pwd )

# Configuration
RELEASE_NAME="${1:-gitops-reverse-engineer}"
NAMESPACE="${2:-gitops-reverse-engineer-system}"
SERVICE_NAME="${RELEASE_NAME}"
SECRET_NAME="${RELEASE_NAME}-certs"

echo "🔐 Generating TLS certificates for Helm deployment..."
echo "📋 Configuration:"
echo "   Release Name: $RELEASE_NAME"
echo "   Namespace: $NAMESPACE"
echo "   Service Name: $SERVICE_NAME"
echo "   Secret Name: $SECRET_NAME"
echo ""

# Create a temporary directory for certificates
TEMP_DIR=$(mktemp -d)
cd "$TEMP_DIR"

echo "📁 Working directory: $TEMP_DIR"

# Generate CA private key
openssl genrsa -out ca.key 2048 2>/dev/null

# Generate CA certificate
openssl req -x509 -new -nodes -key ca.key -subj "/CN=${RELEASE_NAME}-ca" -days 365 -out ca.crt 2>/dev/null

# Generate server private key
openssl genrsa -out tls.key 2048 2>/dev/null

# Create certificate signing request (CSR)
cat > csr.conf <<EOF
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[v3_req]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
[alt_names]
DNS.1 = ${SERVICE_NAME}
DNS.2 = ${SERVICE_NAME}.${NAMESPACE}
DNS.3 = ${SERVICE_NAME}.${NAMESPACE}.svc
DNS.4 = ${SERVICE_NAME}.${NAMESPACE}.svc.cluster.local
EOF

# Generate CSR
openssl req -new -key tls.key -subj "/CN=${SERVICE_NAME}.${NAMESPACE}.svc" -config csr.conf -out tls.csr 2>/dev/null

# Generate server certificate
openssl x509 -req -in tls.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out tls.crt -days 365 -extensions v3_req -extfile csr.conf 2>/dev/null

echo "✅ Certificates generated successfully"

# Create namespace if it doesn't exist
kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f - >/dev/null 2>&1

# Create Kubernetes secret with the certificates
kubectl create secret generic "$SECRET_NAME" \
  --from-file=tls.key=tls.key \
  --from-file=tls.crt=tls.crt \
  --namespace="$NAMESPACE" \
  --dry-run=client -o yaml | kubectl apply -f - >/dev/null

echo "✅ Secret '$SECRET_NAME' created in namespace '$NAMESPACE'"

# Get the CA bundle
CA_BUNDLE=$(cat ca.crt | base64 | tr -d '\n')

# Create Helm values override file
VALUES_OVERRIDE_FILE="${PROJECT_DIR}/values-certs-override.yaml"

cat > "$VALUES_OVERRIDE_FILE" <<EOF
# Auto-generated by generate-certs-helm.sh
# Generated on: $(date)
# Release: ${RELEASE_NAME}
# Namespace: ${NAMESPACE}

tls:
  existingSecret: "${SECRET_NAME}"
  crt: "${CA_BUNDLE}"
EOF

echo "✅ Created Helm values override: $VALUES_OVERRIDE_FILE"

# Also save CA certificate for reference
cp ca.crt "${PROJECT_DIR}/ca.crt"
echo "✅ CA certificate saved to: ${PROJECT_DIR}/ca.crt"

echo ""
echo "🎉 Certificate generation complete!"
echo ""
echo "📝 To deploy with these certificates:"
echo ""
echo "   Option 1 - Using values override file:"
echo "   helm template ${RELEASE_NAME} ./chart \\"
echo "     -f values-certs-override.yaml \\"
echo "     --namespace ${NAMESPACE} | kubectl apply -f -"
echo ""
echo "   Option 2 - Using Makefile:"
echo "   make deploy TAG=your-tag"
echo ""
echo "   Option 3 - Direct helm command:"
echo "   helm template ${RELEASE_NAME} ./chart \\"
echo "     --set tls.existingSecret=${SECRET_NAME} \\"
echo "     --set tls.crt=${CA_BUNDLE} \\"
echo "     --namespace ${NAMESPACE} | kubectl apply -f -"
echo ""

# Cleanup temp directory
cd -
rm -rf "$TEMP_DIR"
